export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const GET_TO_CART_LOADING = "GET_TO_CART_LOADING";
export const GET_TO_CART_SUCCESS = "GET_TO_CART_SUCCESS";
export const GET_TO_CART_FAILURE = "GET_TO_CART_FAILURE";

export const UPDATE_TO_CART_LOADING = "UPDATE_TO_CART_LOADING";
export const UPDATE_TO_CART_SUCCESS = "UPDATE_TO_CART_SUCCESS";
export const UPDATE_TO_CART_FAILURE = "UPDATE_TO_CART_FAILURE";

export const REMOVE_TO_CART_LOADING = "REMOVE_TO_CART_LOADING";
export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const REMOVE_TO_CART_FAILURE = "REMOVE_TO_CART_FAILURE";
